package com.binitech.elosys.domain.sanction;

public record SanctionRow(
    String registry,
    String sanctionCode,
    String personType,
    String cpfCnpj,
    String sanctionedName,
    String sanctionedNameReported,
    String legalName,
    String tradeName,
    String processNumber,
    String category,
    Long fineAmountCents,
    String startDate,
    String endDate,
    String publicationDate,
    String publication,
    String publicationDetail,
    String finalJudgmentDate,
    String scope,
    String sanctioningAgency,
    String agencyState,
    String agencySphere,
    String legalBasis,
    String sourceDataDate,
    String sourceOrigin,
    String notes,
    Long companyId,
    Long personId,
    long provenanceId) {}
