package com.binitech.elosys.domain.candidate;

public record CandidateRow(
    String cpf,
    String voterId,
    String ballotName,
    String fullName,
    String normalizedName,
    String tseCandidacyId,
    int year,
    String electionType,
    Integer round,
    String office,
    String candidateNumber,
    String partyAbbr,
    String partyName,
    String partyNumber,
    String state,
    String electoralUnit,
    String municipality,
    String candidacyStatus,
    String candidacyStatusDetail,
    String result,
    String birthDate,
    String gender,
    String education,
    String maritalStatus,
    String race,
    String occupation,
    long provenanceId) {

  public CandidateRow withCpf(String newCpf) {
    return new CandidateRow(
        newCpf,
        voterId,
        ballotName,
        fullName,
        normalizedName,
        tseCandidacyId,
        year,
        electionType,
        round,
        office,
        candidateNumber,
        partyAbbr,
        partyName,
        partyNumber,
        state,
        electoralUnit,
        municipality,
        candidacyStatus,
        candidacyStatusDetail,
        result,
        birthDate,
        gender,
        education,
        maritalStatus,
        race,
        occupation,
        provenanceId);
  }
}
