CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE source (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    agency      text NOT NULL,
    type        text NOT NULL,
    base_url    text NOT NULL,
    legal_basis text,
    notes       text,
    created_at  timestamptz NOT NULL
);

CREATE TABLE collection (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id        bigint NOT NULL REFERENCES source(id),
    url              text NOT NULL,
    http_status      integer,
    accessed_at      timestamptz NOT NULL,
    payload_sha256   text NOT NULL,
    size_bytes       bigint NOT NULL,
    content_type     text,
    collector_commit text,
    notes            text
);
CREATE INDEX ix_collection_dedup ON collection (url, payload_sha256);
CREATE INDEX ix_collection_source ON collection (source_id);

CREATE TABLE collection_file (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id bigint NOT NULL REFERENCES collection(id),
    filename      text NOT NULL,
    sha256        text NOT NULL,
    size_bytes    bigint NOT NULL,
    UNIQUE (collection_id, filename)
);

CREATE TABLE parse (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id      bigint NOT NULL REFERENCES collection(id),
    collection_file_id bigint REFERENCES collection_file(id),
    parser_name        text NOT NULL,
    parser_commit      text,
    parser_version     text NOT NULL,
    rows_extracted     bigint NOT NULL DEFAULT 0,
    rows_rejected      bigint NOT NULL DEFAULT 0,
    run_at             timestamptz NOT NULL
);
CREATE INDEX ix_parse_collection ON parse (collection_id);

CREATE TABLE record_sources (
    table_name text NOT NULL,
    record_id  bigint NOT NULL,
    field      text NOT NULL DEFAULT '',
    parse_id   bigint NOT NULL REFERENCES parse(id),
    PRIMARY KEY (table_name, record_id, field, parse_id)
);

CREATE TABLE people (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf            text,
    cpf_trusted    boolean NOT NULL DEFAULT false,
    voter_id       text,
    canonical_name text,
    created_at     timestamptz NOT NULL
);
CREATE INDEX ix_people_cpf            ON people (cpf) WHERE cpf IS NOT NULL;
CREATE INDEX ix_people_voter_id       ON people (voter_id) WHERE voter_id IS NOT NULL;
CREATE INDEX ix_people_canonical_name ON people (canonical_name);
CREATE INDEX ix_people_canonical_name_trgm ON people USING gin (canonical_name gin_trgm_ops);

CREATE TABLE rejected_cpf (
    cpf                text PRIMARY KEY,
    reason             text NOT NULL,
    distinct_voter_ids integer,
    distinct_names     integer,
    recorded_at        timestamptz NOT NULL
);

CREATE TABLE companies (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj       text NOT NULL UNIQUE,
    legal_name text,
    kind       text,
    created_at timestamptz NOT NULL
);
CREATE INDEX ix_companies_legal_name_trgm ON companies USING gin (legal_name gin_trgm_ops);

CREATE TABLE campaign_org (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       bigint NOT NULL REFERENCES companies(id),
    person_id        bigint REFERENCES people(id),
    cnpj             text NOT NULL,
    tse_candidacy_id text,
    accountant_id    text,
    year             integer NOT NULL,
    candidate_cpf    text,
    candidate_name   text,
    normalized_name  text,
    office           text,
    party_abbr       text,
    state            text,
    provenance_id    bigint NOT NULL REFERENCES parse(id),
    collected_at     timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_campaign_org ON campaign_org (year, tse_candidacy_id, cnpj);
CREATE INDEX ix_campaign_org_person ON campaign_org (person_id);
CREATE INDEX ix_campaign_org_cnpj   ON campaign_org (cnpj);

CREATE TABLE campaign_donation (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_org_id        bigint REFERENCES campaign_org(id),
    cnpj                   text NOT NULL,
    tse_candidacy_id       text,
    year                   integer NOT NULL,
    tse_receipt_id         text,
    receipt_number         text,
    document_id            text,
    receipt_date           text,
    amount_cents           bigint,
    source                 text,
    origin                 text,
    species                text,
    donor_cpf_cnpj         text,
    donor_name             text,
    donor_name_rfb         text,
    donor_cnae             text,
    donor_state            text,
    donor_municipality     text,
    donor_tse_candidacy_id text,
    donor_party_abbr       text,
    donor_person_id        bigint REFERENCES people(id),
    donor_company_id       bigint REFERENCES companies(id),
    provenance_id          bigint NOT NULL REFERENCES parse(id),
    collected_at           timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_campaign_donation ON campaign_donation (year, tse_receipt_id);
CREATE INDEX ix_campaign_donation_org          ON campaign_donation (campaign_org_id);
CREATE INDEX ix_campaign_donation_candidacy    ON campaign_donation (year, tse_candidacy_id);
CREATE INDEX ix_campaign_donation_donor_doc    ON campaign_donation (donor_cpf_cnpj text_pattern_ops);
CREATE INDEX ix_campaign_donation_donor_person ON campaign_donation (donor_person_id) WHERE donor_person_id IS NOT NULL;
CREATE INDEX ix_campaign_donation_donor_company ON campaign_donation (donor_company_id) WHERE donor_company_id IS NOT NULL;
CREATE INDEX ix_campaign_donation_donor_name   ON campaign_donation (donor_name) WHERE donor_company_id IS NULL;

CREATE TABLE campaign_expense (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_org_id           bigint REFERENCES campaign_org(id),
    cnpj                      text NOT NULL,
    tse_candidacy_id          text,
    year                      integer NOT NULL,
    tse_expense_id            text,
    document_type             text,
    document_number           text,
    expense_date              text,
    amount_cents              bigint,
    origin                    text,
    description               text,
    supplier_cpf_cnpj         text,
    supplier_name             text,
    supplier_name_rfb         text,
    supplier_type             text,
    supplier_cnae             text,
    supplier_state            text,
    supplier_municipality     text,
    supplier_tse_candidacy_id text,
    supplier_party_abbr       text,
    supplier_person_id        bigint REFERENCES people(id),
    supplier_company_id       bigint REFERENCES companies(id),
    provenance_id             bigint NOT NULL REFERENCES parse(id),
    collected_at              timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_campaign_expense ON campaign_expense (year, tse_expense_id);
CREATE INDEX ix_campaign_expense_org          ON campaign_expense (campaign_org_id);
CREATE INDEX ix_campaign_expense_candidacy    ON campaign_expense (year, tse_candidacy_id);
CREATE INDEX ix_campaign_expense_supplier_doc ON campaign_expense (supplier_cpf_cnpj text_pattern_ops);
CREATE INDEX ix_campaign_expense_supplier_person ON campaign_expense (supplier_person_id) WHERE supplier_person_id IS NOT NULL;
CREATE INDEX ix_campaign_expense_supplier_company ON campaign_expense (supplier_company_id) WHERE supplier_company_id IS NOT NULL;
CREATE INDEX ix_campaign_expense_supplier_name ON campaign_expense (supplier_name) WHERE supplier_company_id IS NULL;
CREATE INDEX ix_campaign_expense_supplier_rank_year
    ON campaign_expense (year, supplier_cpf_cnpj) WHERE supplier_company_id IS NOT NULL;
CREATE INDEX ix_campaign_expense_description_trgm ON campaign_expense USING gin (description gin_trgm_ops);

CREATE TABLE pessoa_fisica_search (
    cpf  text PRIMARY KEY,
    name text,
    tsv  tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(name, ''))) STORED
);
CREATE INDEX ix_pessoa_fisica_search_tsv ON pessoa_fisica_search USING gin (tsv);

CREATE TABLE campaign_expense_payment (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_expense_id bigint REFERENCES campaign_expense(id),
    tse_expense_id      text,
    tse_installment_id  text,
    accountant_id       text,
    year                integer NOT NULL,
    state               text,
    document_type       text,
    document_number     text,
    payment_date        text,
    amount_cents        bigint,
    source              text,
    origin              text,
    nature              text,
    species             text,
    description         text,
    provenance_id       bigint NOT NULL REFERENCES parse(id),
    collected_at        timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_campaign_expense_payment
    ON campaign_expense_payment (year, tse_expense_id, tse_installment_id);
CREATE INDEX ix_campaign_expense_payment_expense ON campaign_expense_payment (campaign_expense_id);

CREATE TABLE social_media (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id        bigint REFERENCES people(id),
    tse_candidacy_id text NOT NULL,
    year             integer NOT NULL,
    state            text,
    platform         text NOT NULL,
    url              text NOT NULL,
    order_in_source  integer,
    provenance_id    bigint NOT NULL REFERENCES parse(id),
    collected_at     timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_social_media ON social_media (year, tse_candidacy_id, url);
CREATE INDEX ix_social_media_person ON social_media (person_id);

CREATE TABLE politician_history (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id               bigint NOT NULL REFERENCES people(id),
    cpf                     text,
    cpf_trusted             boolean NOT NULL,
    voter_id                text,
    ballot_name             text,
    full_name               text,
    normalized_name         text,
    tse_candidacy_id        text,
    year                    integer NOT NULL,
    election_type           text,
    round                   integer,
    office                  text,
    candidate_number        text,
    party_abbr              text,
    party_name              text,
    party_number            text,
    state                   text,
    electoral_unit          text,
    municipality            text,
    candidacy_status        text,
    candidacy_status_detail text,
    result                  text,
    birth_date              text,
    gender                  text,
    education               text,
    marital_status          text,
    race                    text,
    occupation              text,
    provenance_id           bigint NOT NULL REFERENCES parse(id),
    collected_at            timestamptz NOT NULL
);
CREATE INDEX ix_ph_person      ON politician_history (person_id);
CREATE INDEX ix_ph_year_office ON politician_history (year, office, state);
CREATE INDEX ix_ph_voter_id    ON politician_history (voter_id) WHERE voter_id IS NOT NULL;
CREATE INDEX ix_ph_candidacy   ON politician_history (tse_candidacy_id);
CREATE INDEX ix_ph_ballot_name_trgm ON politician_history USING gin (ballot_name gin_trgm_ops);
CREATE UNIQUE INDEX ux_ph_candidacy
    ON politician_history (year, tse_candidacy_id, round)
    WHERE tse_candidacy_id IS NOT NULL;

CREATE TABLE rule_run (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule           text NOT NULL,
    rule_version   text NOT NULL,
    code_commit    text,
    params         jsonb,
    run_at         timestamptz NOT NULL,
    rows_generated bigint NOT NULL DEFAULT 0
);
CREATE INDEX ix_rule_run_rule ON rule_run (rule);

CREATE TABLE signal (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_run_id  bigint NOT NULL REFERENCES rule_run(id),
    type         text NOT NULL,
    severity     text NOT NULL,
    explanation  text NOT NULL,
    amount_cents bigint,
    path_length  integer
);
CREATE INDEX ix_signal_rule_run ON signal (rule_run_id);

CREATE TABLE signal_actor (
    signal_id bigint NOT NULL REFERENCES signal(id),
    type      text NOT NULL,
    actor_id  bigint NOT NULL,
    role      text NOT NULL,
    PRIMARY KEY (signal_id, type, actor_id, role)
);
CREATE INDEX ix_signal_actor_actor ON signal_actor (type, actor_id);

CREATE TABLE signal_evidence (
    signal_id  bigint NOT NULL REFERENCES signal(id),
    table_name text NOT NULL,
    record_id  bigint NOT NULL,
    PRIMARY KEY (signal_id, table_name, record_id)
);

CREATE TABLE signal_ai_review (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id         bigint NOT NULL REFERENCES signal(id),
    model             text NOT NULL,
    reviewed_at       timestamptz NOT NULL,
    verdict           text NOT NULL,
    confidence        text,
    explanation       text NOT NULL,
    facts             jsonb,
    prompt            text NOT NULL,
    raw_response      text NOT NULL,
    tokens_prompt     integer,
    tokens_completion integer
);
CREATE UNIQUE INDEX ux_signal_ai_review ON signal_ai_review (signal_id, model);
CREATE INDEX ix_signal_ai_review_verdict ON signal_ai_review (verdict);

CREATE TABLE sanction (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry                 text NOT NULL,
    sanction_code            text NOT NULL,
    person_type              text,
    cpf_cnpj                 text NOT NULL,
    sanctioned_name          text,
    sanctioned_name_reported text,
    legal_name               text,
    trade_name               text,
    process_number           text,
    category                 text,
    fine_amount_cents        bigint,
    start_date               text,
    end_date                 text,
    publication_date         text,
    publication              text,
    publication_detail       text,
    final_judgment_date      text,
    scope                    text,
    sanctioning_agency       text,
    agency_state             text,
    agency_sphere            text,
    legal_basis              text,
    source_data_date         text,
    source_origin            text,
    notes                    text,
    company_id               bigint REFERENCES companies(id),
    person_id                bigint REFERENCES people(id),
    provenance_id            bigint NOT NULL REFERENCES parse(id),
    collected_at             timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_sanction ON sanction (registry, sanction_code);
CREATE INDEX ix_sanction_cpf_cnpj ON sanction (cpf_cnpj);
CREATE INDEX ix_sanction_company ON sanction (company_id) WHERE company_id IS NOT NULL;
CREATE INDEX ix_sanction_person ON sanction (person_id) WHERE person_id IS NOT NULL;

CREATE TABLE parliamentary_earmark (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    earmark_code       text NOT NULL,
    year               integer NOT NULL,
    earmark_type       text,
    author_code        text,
    author_name        text,
    author_person_id   bigint REFERENCES people(id),
    author_match_basis text,
    locality           text,
    state              text,
    municipality       text,
    function_name      text,
    subfunction_name   text,
    program_name       text,
    action_name        text,
    committed_cents    bigint,
    paid_cents         bigint,
    provenance_id      bigint NOT NULL REFERENCES parse(id),
    collected_at       timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_parliamentary_earmark
    ON parliamentary_earmark (earmark_code, year, locality);
CREATE INDEX ix_parliamentary_earmark_author
    ON parliamentary_earmark (author_person_id) WHERE author_person_id IS NOT NULL;

CREATE TABLE parliamentary_earmark_beneficiary (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    earmark_code           text NOT NULL,
    author_code            text,
    year_month             text,
    beneficiary_doc        text NOT NULL,
    beneficiary_name       text,
    beneficiary_type       text,
    beneficiary_company_id bigint REFERENCES companies(id),
    state                  text,
    municipality           text,
    amount_cents           bigint NOT NULL,
    provenance_id          bigint NOT NULL REFERENCES parse(id),
    collected_at           timestamptz NOT NULL
);
CREATE INDEX ix_earmark_beneficiary_code ON parliamentary_earmark_beneficiary (earmark_code);
CREATE INDEX ix_earmark_beneficiary_company
    ON parliamentary_earmark_beneficiary (beneficiary_company_id) WHERE beneficiary_company_id IS NOT NULL;

CREATE TABLE declared_assets (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id         bigint REFERENCES people(id),
    history_id        bigint REFERENCES politician_history(id),
    tse_candidacy_id  text NOT NULL,
    year              integer NOT NULL,
    state             text,
    asset_order       integer,
    asset_type        text,
    description       text,
    value_cents       bigint,
    source_updated_at text,
    provenance_id     bigint NOT NULL REFERENCES parse(id),
    collected_at      timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_declared_assets
    ON declared_assets (year, tse_candidacy_id, asset_order);
CREATE INDEX ix_declared_assets_person  ON declared_assets (person_id) WHERE person_id IS NOT NULL;
CREATE INDEX ix_declared_assets_history ON declared_assets (history_id) WHERE history_id IS NOT NULL;

CREATE TABLE candidate_photo (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id        bigint REFERENCES people(id),
    history_id       bigint REFERENCES politician_history(id),
    tse_candidacy_id text NOT NULL,
    year             integer,
    photo_url        text NOT NULL,
    provenance_id    bigint NOT NULL REFERENCES parse(id),
    collected_at     timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_candidate_photo ON candidate_photo (year, tse_candidacy_id);
CREATE INDEX ix_candidate_photo_person ON candidate_photo (person_id) WHERE person_id IS NOT NULL;

CREATE TABLE company_registry (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           bigint NOT NULL REFERENCES companies(id),
    cnpj                 text NOT NULL,
    legal_name           text,
    trade_name           text,
    opened_at            text,
    registry_status      text,
    registry_status_date text,
    legal_nature         text,
    primary_cnae         text,
    share_capital_cents  bigint,
    size                 text,
    city                 text,
    state                text,
    provenance_id        bigint NOT NULL REFERENCES parse(id),
    collected_at         timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_company_registry ON company_registry (company_id);

CREATE TABLE company_partner (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         bigint NOT NULL REFERENCES companies(id),
    cnpj               text NOT NULL,
    partner_name       text NOT NULL,
    partner_doc_masked text,
    role               text,
    entry_date         text,
    provenance_id      bigint NOT NULL REFERENCES parse(id),
    collected_at       timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_company_partner
    ON company_partner (company_id, partner_name, entry_date);
CREATE INDEX ix_company_partner_company ON company_partner (company_id);

CREATE TABLE candidate_supplier_partner (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id            bigint NOT NULL REFERENCES people(id),
    company_id           bigint NOT NULL REFERENCES companies(id),
    company_partner_id   bigint NOT NULL REFERENCES company_partner(id),
    match_basis          text NOT NULL,
    partner_role         text,
    partner_since        text,
    payments_total_cents bigint NOT NULL DEFAULT 0,
    payments_count       bigint NOT NULL DEFAULT 0,
    payer_candidacies    bigint NOT NULL DEFAULT 0,
    paid_by_self         boolean NOT NULL DEFAULT false,
    computed_at          timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_csp ON candidate_supplier_partner (person_id, company_id);
CREATE INDEX ix_csp_amount ON candidate_supplier_partner (payments_total_cents);

CREATE TABLE social_account (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id              bigint REFERENCES people(id),
    network                text NOT NULL,
    handle                 text NOT NULL,
    handle_declared        text,
    external_id            text,
    declared_provenance_id bigint REFERENCES parse(id),
    source_id              bigint REFERENCES source(id),
    status                 text,
    first_seen_at          timestamptz NOT NULL,
    last_crawled_at        timestamptz,
    UNIQUE (network, handle)
);
CREATE INDEX ix_social_account_person ON social_account (person_id);

CREATE TABLE social_post (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_account_id    bigint NOT NULL REFERENCES social_account(id),
    external_id          text NOT NULL,
    kind                 text NOT NULL,
    lang                 text,
    text                 text NOT NULL,
    in_reply_to_external text,
    reply_to_handle      text,
    posted_at            text,
    like_count           bigint,
    repost_count         bigint,
    reply_count          bigint,
    url                  text,
    matched_terms        jsonb,
    matched_query        text,
    apify_run_id         text,
    raw_json             text NOT NULL,
    raw_sha256           text NOT NULL,
    retrieved_at         timestamptz NOT NULL,
    UNIQUE (social_account_id, external_id)
);

CREATE TABLE social_post_review (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_post_id    bigint NOT NULL REFERENCES social_post(id),
    model             text NOT NULL,
    reviewed_at       timestamptz NOT NULL,
    categories        jsonb,
    severity          text,
    is_offensive      boolean,
    quote             text,
    explanation       text,
    prompt            text,
    raw_response      text,
    tokens_prompt     integer,
    tokens_completion integer,
    UNIQUE (social_post_id, model)
);
CREATE INDEX ix_social_post_review_sev ON social_post_review (severity);

CREATE TABLE job_run (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job         text NOT NULL,
    params      jsonb,
    status      text NOT NULL,
    started_at  timestamptz NOT NULL,
    finished_at timestamptz,
    report      jsonb,
    error       text
);
CREATE INDEX ix_job_run_job ON job_run (job, started_at DESC);
